version: 2.1
orbs:
  node: circleci/node@4.7.0
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.8.1

jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Package Install
          command: yarn
      - run:
          name: Run E2E Tests
          command: $(npm bin)/cypress run
      - slack/notify:
          event: pass
          channel: deploy
          mentions: '@here'

workflows:
  build:
    jobs:
      - build
