import type { NextPage } from "next";
import Head from "next/head";
import Pads from "@/components/organismus/Pads";
import { containerCls, mainCls, titleCls } from "./index.css";

/**
 * パッド
 */
const Home: NextPage = () => {
  return (
    <div className={containerCls}>
      <Head>
        <title>iDeath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={mainCls}>
        <h1 className={titleCls}>Pads</h1>
        <div>
          <Pads />
        </div>
      </main>
    </div>
  );
};

export default Home;
