import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useCallback } from "react";
import Icons from "@/components/atoms/Icons";
import * as styles from "@/styles/index.css";

/**
 * TOP
 */
const Home: NextPage = () => {
  const router = useRouter();
  const handleLoginBtnClick = useCallback(() => {
    router.push("/seq");
  }, [router]);

  return (
    <div className={styles.containerCls}>
      <Head>
        <title>iDeath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainCls}>
        <div className={styles.heroImage}>
          <div className={styles.heroText}>
            <h1 className={styles.titleCls}>
              iDeath
              <br />
              is cloud music gear
            </h1>
          </div>
          <div className={styles.btnAreaCls}>
            <button
              className={styles.loginBtnCls}
              onClick={handleLoginBtnClick}
            >
              Enter
              <Icons name="Login" />
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
