import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useCallback } from "react";
import MainLayout from "@/components/layouts/MainLayout";
import SquareButton from "@/components/atoms/SquareButton";
import MotionImage from "@/components/atoms/MotionImage";
import MotionText from "@/components/atoms/MotionText";
import BaseFooter from "@/components/layouts/BaseFooter";
import { motion } from "framer-motion";
import * as styles from "@/styles/index.css";

/**
 * TOP
 */
const Home: NextPage = () => {
  const router = useRouter();

  const handleSelectSeqClick = useCallback(() => {
    router.push("/seq");
  }, [router]);

  const handleSelectFMClick = useCallback(() => {
    router.push("/fm");
  }, [router]);

  const placeholderText = [
    { type: "heading1", text: "Please select the gear you want to use." },
  ];

  return (
    <div className={styles.containerCls}>
      <Head>
        <title>iDeath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className={styles.heroImage}>
          <div className={styles.heroText}>
            <motion.div
              className="App"
              initial="hidden"
              animate="visible"
              variants={{
                visible: {
                  transition: {
                    staggerChildren: 0.025,
                  },
                },
              }}
            >
              <MotionText {...placeholderText[0]} />
            </motion.div>
          </div>
        </div>
        <section>
          <div className={styles.gearsSection}>
            <MotionImage
              src="/images/top/seq.png"
              width={720}
              height={420}
              objectFit="contain"
              alt="seq"
            />
            <div className={styles.gearsSectionDetail}>
              <h2>Seq</h2>
              <dl>
                <dt>Features</dt>
                <dd>
                  <ul className={styles.gearsSectionDetailList}>
                    <li>6 track sampler</li>
                    <li>16 step sequencer</li>
                  </ul>
                </dd>
                <dt>Sounds</dt>
                <dd>
                  <ul className={styles.gearsSectionDetailList}>
                    <li>presets drum samles</li>
                  </ul>
                </dd>
                <dt>Effects</dt>
                <dd>
                  <ul className={styles.gearsSectionDetailList}>
                    <li>Reverb</li>
                    <li>Distortion</li>
                  </ul>
                </dd>
              </dl>
              <div className={styles.btnArea}>
                <SquareButton
                  label="SELECT"
                  small
                  onClick={handleSelectSeqClick}
                />
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className={styles.gearsSection}>
            <MotionImage
              src="/images/top/fm.png"
              width={720}
              height={420}
              objectFit="contain"
              alt="seq"
            />
            <div className={styles.gearsSectionDetail}>
              <h2>FM</h2>
              <dl>
                <dt>Features</dt>
                <dd>
                  <ul className={styles.gearsSectionDetailList}>
                    <li>1 voice FM Synthesizer</li>
                    <li>24 keys</li>
                    <li>16 step sequencer</li>
                  </ul>
                </dd>
                <dt>Effects</dt>
                <dd>
                  <ul className={styles.gearsSectionDetailList}>
                    <li>Reverb</li>
                    <li>Delay</li>
                    <li>Distortion</li>
                  </ul>
                </dd>
              </dl>
              <div className={styles.btnArea}>
                <SquareButton
                  label="SELECT"
                  small
                  onClick={handleSelectFMClick}
                />
              </div>
            </div>
          </div>
        </section>
      </MainLayout>
      <BaseFooter />
    </div>
  );
};

export default Home;
