import * as Tone from "tone";
import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import * as styles from "@/styles/org.css";

const Sketch = dynamic(import("react-p5"), { ssr: false });

export const SketchComponent = () => {
  const preload = () => {};

  const setup = (p5: any, canvasParentRef: Element) => {
    p5.createCanvas(p5.windowWidth, p5.windowHeight).parent(canvasParentRef);
    p5.noStroke();
    p5.frameRate(30);
  };

  const draw = (p5: any) => {
    p5.background(225);
    p5.stroke(255);
  };

  const windowResized = (p5: any) => {
    p5.resizeCanvas(p5.windowWidth, p5.windowHeight);
  };

  const touchStarted = (p5: any) => {
    Tone.Transport.start();
    Tone.Transport.bpm.value = 160;

    const player = new Tone.Player({
      url: "/samples/808/CB.WAV",
      autostart: true,
    }).toDestination();

    const filter = new Tone.Filter(200, "lowpass").toDestination();

    player.connect(filter);
  };

  return (
    <Sketch
      preload={preload}
      setup={setup}
      draw={draw}
      windowResized={windowResized}
      touchStarted={touchStarted}
    />
  );
};

/**
 * トラッカー
 */
const Org: NextPage = () => {
  return (
    <div className={styles.containerCls}>
      <Head>
        <title>iDeath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainCls}>
        <h1 className={styles.titleCls}>Org</h1>
        <div>
          <SketchComponent />
        </div>
      </main>
    </div>
  );
};

export default Org;
